name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  
  workflow_dispatch:              
  push:                           
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rose811            

        
          plugin_anilist: yes
          plugin_anilist_user: rose811    
          plugin_anilist_medias: anime                  
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit_characters: 10
